downloadserver = "https://raw.githubusercontent.com/Lfrxxofficial/XenOS/refs/heads/main/1.0/"
term.setBackgroundColor(colors.green)
term.clear()
term.setCursorPos(1,1)
term.write("Welcome To the installer of XenOs")
term.setCursorPos(1,3)
term.write("Download Server is "..downloadserver)
sleep(1)
term.setCursorPos(1,1)
term.write("Installing XenOS")
shell.run("mkdir system")
shell.run("cd system")
shell.run("wget "..downloadserver.."os.lua")
shell.run("cd /")
shell.run("wget "..downloadserver.."startup.lua")
